# Generated by Django 5.1.7 on 2025-03-21 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="last_review_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="schools",
            name="review_summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
