# Generated by Django 5.1.7 on 2025-03-21 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0002_schools_last_review_date_schools_review_summary"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="review_dates",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="schools",
            name="review_summaries",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="schools",
            name="sport_review_dates",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AddField(
            model_name="schools",
            name="sport_summaries",
            field=models.JSONField(blank=True, default=dict, null=True),
        ),
    ]
