# Generated by Django 5.2 on 2025-04-29 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_schools_review_dates_schools_review_summaries_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="vb",
            field=models.BooleanField(default=False),
        ),
    ]
