# Generated by Django 5.2 on 2025-04-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0004_schools_vb"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schools",
            name="vb",
            field=models.BooleanField(),
        ),
    ]
