# Generated by Django 5.2 on 2025-04-30 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0006_rename_vb_schools_wvb"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schools",
            old_name="wvb",
            new_name="vb",
        ),
    ]
