# Generated by Django 5.2 on 2025-04-30 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0007_rename_wvb_schools_vb"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="ba",
            field=models.BooleanField(default=True),
        ),
    ]
