# Generated by Django 5.2 on 2025-05-01 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0008_schools_ba"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="wsoc",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="schools",
            name="ba",
            field=models.BooleanField(),
        ),
    ]
