# Generated by Django 5.2 on 2025-05-01 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0010_schools_wr_alter_schools_wsoc"),
    ]

    operations = [
        migrations.AlterField(
            model_name="schools",
            name="vb",
            field=models.BooleanField(default=True),
        ),
    ]
