# Generated by Django 5.2 on 2025-05-01 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0012_alter_schools_ba_alter_schools_wsoc"),
    ]

    operations = [
        migrations.AddField(
            model_name="schools",
            name="msoc",
            field=models.BooleanField(default=False),
        ),
    ]
