# Generated by Django 5.1.6 on 2025-02-13 23:41

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0002_alter_reviews_review_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="review_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
