# Generated by Django 5.1.6 on 2025-02-16 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0003_alter_reviews_review_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="head_coach_name",
            field=models.TextField(blank=True, null=True),
        ),
    ]
