# Generated by Django 5.1.6 on 2025-02-16 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0004_reviews_head_coach_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reviews",
            name="head_coach_name",
            field=models.TextField(default="Unknown"),
            preserve_default=False,
        ),
    ]
