# Generated by Django 5.1.6 on 2025-02-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0005_alter_reviews_head_coach_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="date_of_review",
        ),
    ]
