# Generated by Django 5.1.6 on 2025-02-18 20:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0006_remove_reviews_date_of_review"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reviews",
            name="sport",
        ),
    ]
