# Generated by Django 5.1.6 on 2025-02-18 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0007_remove_reviews_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="sport",
            field=models.CharField(default="Sport", max_length=255),
            preserve_default=False,
        ),
    ]
