# Generated by Django 5.2 on 2025-04-22 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0008_reviews_sport"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="coach_history",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="reviews",
            name="coach_no_longer_at_university",
            field=models.BooleanField(default=False),
        ),
    ]
