# Generated by Django 5.2 on 2025-04-22 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0009_reviews_coach_history_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="reviews",
            name="summary",
            field=models.TextField(blank=True, null=True),
        ),
    ]
