# Generated by Django 5.2 on 2025-04-23 00:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0010_reviews_summary"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviews",
            options={"verbose_name_plural": "Reviews"},
        ),
        migrations.AddField(
            model_name="reviews",
            name="sentiment_label",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="reviews",
            name="sentiment_score",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="created_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="head_coach_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="updated_at",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
