# Generated by Django 5.2 on 2025-04-23 01:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reviews", "0011_alter_reviews_options_reviews_sentiment_label_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="reviews",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "Review",
                "verbose_name_plural": "Reviews",
            },
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="sentiment_label",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="sentiment_score",
        ),
        migrations.RemoveField(
            model_name="reviews",
            name="summary",
        ),
        migrations.AlterField(
            model_name="reviews",
            name="coach_history",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="head_coach_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="review_id",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="sport",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="reviews",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
