# Generated by Django 5.1.6 on 2025-02-07 03:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Schools',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_id', models.CharField(max_length=255)),
                ('school_name', models.CharField(max_length=255)),
                ('mbb', models.BooleanField(default=False)),
                ('wbb', models.BooleanField(default=False)),
                ('fb', models.BooleanField(default=False)),
                ('conference', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('transfer_in_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_in_school', to='users.schools')),
                ('transfer_out_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transfer_out_school', to='users.schools')),
            ],
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=255)),
                ('review_message', models.TextField()),
                ('head_coach', models.IntegerField()),
                ('assistant_coaches', models.IntegerField()),
                ('team_culture', models.IntegerField()),
                ('campus_life', models.IntegerField()),
                ('athletic_facilities', models.IntegerField()),
                ('athletic_department', models.IntegerField()),
                ('player_development', models.IntegerField()),
                ('nil_opportunity', models.IntegerField()),
                ('date_of_review', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.schools')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
        ),
    ]
