# Generated by Django 5.1.6 on 2025-02-07 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schools',
            name='school_id',
        ),
        migrations.AddField(
            model_name='users',
            name='session_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='schools',
            name='conference',
            field=models.CharField(max_length=100),
        ),
    ]
