# Generated by Django 5.1.6 on 2025-02-13 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_remove_users_session_token_users_groups_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="transfer_type",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
