# Generated by Django 5.1.7 on 2025-03-24 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0008_users_reset_token"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_school_verified",
            field=models.BooleanField(default=False),
        ),
    ]
