# Generated by Django 5.1.7 on 2025-03-30 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_users_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_picture",
            field=models.CharField(
                choices=[
                    ("profile1.png", "Profile 1"),
                    ("profile2.png", "Profile 2"),
                    ("profile3.png", "Profile 3"),
                    ("profile4.png", "Profile 4"),
                    ("profile5.png", "Profile 5"),
                ],
                default="default.png",
                max_length=255,
            ),
        ),
    ]
