# Generated by Django 5.1.7 on 2025-03-30 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0012_alter_users_profile_picture"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_picture",
            field=models.CharField(
                choices=[("pic1.jpg", "Profile 1"), ("pic2.jpg", "Profile 2")],
                default="pic1.jpg",
                max_length=255,
            ),
        ),
    ]
