# Generated by Django 5.1.7 on 2025-03-31 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0014_users_profile_picture_modified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="users",
            name="profile_picture_modified",
        ),
    ]
