# Generated by Django 5.1.7 on 2025-03-31 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0015_remove_users_profile_picture_modified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="users",
            name="profile_picture",
            field=models.CharField(
                choices=[
                    ("pic1.png", "Profile 1"),
                    ("pic2.png", "Profile 2"),
                    ("pic3.png", "Profile 3"),
                    ("pic4.png", "Profile 4"),
                    ("pic5.png", "Profile 5"),
                ],
                default="pic1.png",
                max_length=255,
            ),
        ),
    ]
